language: python

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  include:
    - os: linux
      language: cpp
      compiler: gcc
      env: PYTHON_VER=3.6
    - os: linux
      language: cpp
      compiler: gcc
      env: PYTHON_VER=3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - cmake
    - cmake-data
    - doxygen
    - libblas-dev
    - libcr-dev
    - libfftw3-dev
    - liblapack-dev
    - libmpich-dev
    - libxml2-dev
    - mpich

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Set up compilers
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Install gromacs
  - source devtools/travis-ci/install_gmx_devel.sh
    # Install gmxapi
  - source devtools/travis-ci/install_gmxapi_devel.sh 
    # Install plugins
  - source devtools/travis-ci/install_sample_restraint.sh
    # Build and install package
  - python setup.py develop --no-deps

script:
  - pytest -v --cov=wzm_wzt wzm_wzt/tests/

notifications:
    email: false

after_success:
  - codecov
