language: python

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  include:
    - os: linux
      language: generic
      env: PYTHON_VER=3.6
    - os: linux
      language: generic
      env: PYTHON_VER=3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - cmake-data
    - doxygen
    - libblas-dev
    - libcr-dev
    - libfftw3-dev
    - liblapack-dev
    - libmpich-dev
    - libxml2-dev
    - mpich

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
    # Activate the test environment
  - conda activate test

    # Install gromacs
  - source devtools/travis-ci/install_gmx_2019.sh
    # Install gmxapi
  - source devtools/travis-ci/install_gmxapi.sh
    # Install plugins
  - source devtools/travis-ci/install_sample_restraint.sh
    # Build and install package
  - python setup.py develop --no-deps

script:
  - pytest -v --cov=wzm_wzt wzm_wzt/tests/

notifications:
    email: false

after_success:
  - codecov
